name: my_profile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_animated: ^3.1.0
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/
